"""Add multi-tenancy support

Revision ID: 5c75eacff366
Revises: 
Create Date: 2026-02-12 09:49:17.835834
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5c75eacff366'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tenants_table = op.create_table('tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)

    # Insert a default tenant
    op.bulk_insert(tenants_table, [{'name': 'Global'}])

    # Add tenant_id as nullable
    op.add_column('job_roles', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('skill_progress', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('sctp_courses', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('market_insights', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))

    # Update existing rows
    op.execute('UPDATE job_roles SET tenant_id = 1')
    op.execute('UPDATE users SET tenant_id = 1')
    op.execute('UPDATE skill_progress SET tenant_id = 1')
    
    # Alter columns to be non-nullable
    op.alter_column('job_roles', 'tenant_id', nullable=False)
    op.alter_column('users', 'tenant_id', nullable=False)
    op.alter_column('skill_progress', 'tenant_id', nullable=False)

    op.create_index(op.f('ix_job_roles_tenant_id'), 'job_roles', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'job_roles', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_market_insights_tenant_id'), 'market_insights', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'market_insights', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_sctp_courses_tenant_id'), 'sctp_courses', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sctp_courses', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_skill_progress_tenant_id'), 'skill_progress', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'skill_progress', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_skills_tenant_id'), 'skills', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'skills', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_user_profiles_tenant_id'), 'user_profiles', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'user_profiles', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_user_profiles_tenant_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'tenant_id')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_index(op.f('ix_skills_tenant_id'), table_name='skills')
    op.drop_column('skills', 'tenant_id')
    op.drop_constraint(None, 'skill_progress', type_='foreignkey')
    op.drop_index(op.f('ix_skill_progress_tenant_id'), table_name='skill_progress')
    op.drop_column('skill_progress', 'tenant_id')
    op.drop_constraint(None, 'sctp_courses', type_='foreignkey')
    op.drop_index(op.f('ix_sctp_courses_tenant_id'), table_name='sctp_courses')
    op.drop_column('sctp_courses', 'tenant_id')
    op.drop_constraint(None, 'market_insights', type_='foreignkey')
    op.drop_index(op.f('ix_market_insights_tenant_id'), table_name='market_insights')
    op.drop_column('market_insights', 'tenant_id')
    op.drop_constraint(None, 'job_roles', type_='foreignkey')
    op.drop_index(op.f('ix_job_roles_tenant_id'), table_name='job_roles')
    op.drop_column('job_roles', 'tenant_id')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
