"""Add 2026 forecast fields to market insights

Revision ID: 72056dd75dde
Revises: ebcea26c05e6
Create Date: 2026-02-14 23:52:06.424475
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '72056dd75dde'
down_revision: Union[str, None] = 'ebcea26c05e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_insights', sa.Column('forecast_2026', sa.String(), nullable=True))
    op.add_column('market_insights', sa.Column('outlook', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_insights', 'outlook')
    op.drop_column('market_insights', 'forecast_2026')
    # ### end Alembic commands ###
