"""Add role to User model

Revision ID: f53ffa742e5f
Revises: 5c75eacff366
Create Date: 2026-02-12 14:27:11.746756
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f53ffa742e5f'
down_revision: Union[str, None] = '5c75eacff366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM ('admin', 'member', 'viewer')")
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='role'), nullable=False, server_default='member'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
