"""Change AuditLog details to JSON type with explicit cast

Revision ID: 4506c6ff8edb
Revises: 661d229b4654
Create Date: 2026-02-12 16:50:53.449761
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4506c6ff8edb'
down_revision: Union[str, None] = '661d229b4654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='details::json') # Explicit cast
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='details::text') # Explicit cast
    # ### end Alembic commands ###
