/**
 * @file copilot.dto.ts
 * @description Data Transfer Objects and shared types for the AI Career Copilot.
 */

import {
  IsArray,
  IsNumber,
  IsOptional,
  IsString,
  MinLength,
} from 'class-validator';

// ─── Core Intelligence Types ──────────────────────────────────────────────────

/**
 * Structured career intelligence extracted from a user's resume.
 * Stored in the `careerIntelligence` JSONB column on `UserProfile`.
 */
export interface CareerIntelligence {
  /** e.g. "junior", "mid-level", "senior", "executive" */
  experience_level: string;
  /** Top technical and soft skills identified */
  top_skills: string[];
  /** Industry domains the user has worked in */
  industries: string[];
  /** Key professional strengths */
  strengths: string[];
  /** Areas needing development */
  improvement_areas: string[];
  /** Recommended career paths based on background */
  career_paths: string[];
  /** 2–4 sentence professional summary generated by the LLM */
  professional_summary: string;
  /** ISO timestamp of when this was last computed */
  analyzed_at: string;
}

/**
 * A single milestone in a 12-month career transition plan.
 */
export interface CareerMilestone {
  /** Month number (1–12) */
  month: number;
  /** Short title for this milestone */
  title: string;
  /** Detailed action items for this month */
  actions: string[];
  /** Expected outcome by end of this period */
  outcome: string;
}

/**
 * Structured 12-month career transition plan.
 */
export interface CareerPlan {
  target_role: string;
  total_months: number;
  milestones: CareerMilestone[];
  key_resources: string[];
  singapore_programmes: string[];
}

// ─── Request DTOs ─────────────────────────────────────────────────────────────

/**
 * Request body for triggering career profile extraction from stored resume text.
 */
export class ExtractProfileDto {
  @IsNumber()
  profile_id!: number;
}

/**
 * Request body for the enriched Copilot chat endpoint.
 */
export class CopilotChatDto {
  @IsNumber()
  @IsOptional()
  profile_id?: number;

  @IsArray()
  messages!: Array<{ role: string; content: string }>;

  /**
   * Optional copilot command to trigger a structured analysis instead of free chat.
   * Values: 'analyze_career' | 'career_plan' | 'resume_tips' | 'interview_prep' | 'skill_gap'
   */
  @IsString()
  @IsOptional()
  command?: string;
}

/**
 * Request body for generating a career transition plan.
 */
export class CareerPlanDto {
  @IsNumber()
  profile_id!: number;

  @IsString()
  @IsOptional()
  target_role?: string;

  @IsNumber()
  @IsOptional()
  months?: number;
}

/**
 * Request body for the resume tips endpoint.
 */
export class ResumeTipsDto {
  @IsNumber()
  profile_id!: number;

  @IsString()
  @IsOptional()
  target_role?: string;
}

/**
 * Request body for interview preparation.
 */
export class InterviewPrepDto {
  @IsNumber()
  profile_id!: number;

  @IsString()
  @MinLength(2)
  job_title!: string;
}
